name: Survival
version: '${project.version}'
main: net.extraherz.survival.Survival
api-version: 1.19
authors: [ Extraherz ]
description: Survival Addons for Residence Survival Server

commands:
  particle:
    description: Toggle the particle effects while walking
    aliases:
      - partikel
      - effects
      - effekte
  playtime:
    description: Shows you current playtime, or reloads the playtime animation
  nightrestart: